apiVersion: v1
kind: Namespace
metadata:
  name: tcpdump-sidecar-ns
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tcp-dump-results
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcp-dump-results
  namespace: tcpdump-sidecar-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: tcp-dump-results
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-dump-deployment
  namespace: tcpdump-sidecar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcpdump-sidecar
  template:
    metadata:
      labels:
        app: tcpdump-sidecar
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: service
        image: {{ SERVICE-IMAGE }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      - name: tcpdump
        image: {{ TCPDUMP-IMAGE }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
          - mountPath: "/mnt/dmp"
            name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: tcp-dump-results
